### ISSUE TITLE
suggested locales/en.yml

### ISSUE THREAD

**Issue by DarkSideGeek** [leonko/redmine_pretend#13]
I suggest the following as more appropriate English:

    # English strings go here for Rails i18n
    en:
      button_pretend: 'Pretend To Be This User'
      button_unpretend: 'UNDO'
      pretend_message: 'You are in PRETEND mode. In real life, you are: '

**Comment by leonko** [comment]
Thank you for you support. 4 years ego my English was realy bad. But nowadays it not better)
I fixed 🇬🇧)
